server:
 port: 8092
 servlet:
  context-path: /cliente-service
 error:
    include-stacktrace: never
spring:
 datasource:  
  url: jdbc:mysql://localhost/clientedb?useSSL=false&serverTimezone = GMT
  username: root
  password: 
  hikari:
   connectionTimeout: 30000
   idleTimeout: 60000
   maxLifetime: 60000
   maximumPoolSize: 15
 jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect = org.hibernate.dialect.MySQL5Dialect
 thymeleaf:
  cache: false
logging:
  level:
    root: WARN    


